AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: SAM Template for testing an SQS-triggered Lambda function

Resources:
  LambdaFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: go1.x
      CodeUri: ./cmd/api/
      Environment:
        Variables:
          INFURA_PROJECT_ID: "c510981aace04b1e80506a0ff746b7d2"
          FOUNDING_PRIVATE_KEY: "4a0e1827d9c9c5c10073a5f206272f9dcfb210e4564e227a511d65625a22fde5"
          FOUDING_ADDRESS: "0x1a48d9Df82436122E90583655873a481EA446a0D"
          QUEUE_URL: "https://sqs.us-west-2.amazonaws.com/029646376518/KeygenQueue"
          AWS_REGION: "us-west-2"
      Handler: main
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt LambdaFunctionRole.Arn

  KeygenQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "KeygenQueue"

  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "LambdaExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "LambdaSqsPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "sqs:ReceiveMessage"
                  - "sqs:DeleteMessage"
                  - "sqs:GetQueueAttributes"
                Resource: !GetAtt KeygenQueue.Arn

  LambdaFunctionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "LambdaFunctionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "LambdaFunctionPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
              - Effect: "Allow"
                Action: ["sqs:*"]
                Resource: "*"

  LambdaFunctionEventSourceMapping:
    Type: "AWS::Lambda::EventSourceMapping"
    Properties:
      EventSourceArn: !GetAtt KeygenQueue.Arn
      FunctionName: !GetAtt LambdaFunction.Arn

  Api:
    Type: "AWS::Serverless::Api"
    Properties:
      StageName: Prod
      DefinitionBody:
        openapi: "3.0.1"
        info:
          title: "eth-keygen-api"
        paths:
          /sign:
            post:
              x-amazon-apigateway-integration:
                type: "AWS"
                httpMethod: "POST"
                uri: !Sub arn:aws:apigateway:${AWS::Region}:sqs:path/KeygenQueue
                passthroughBehavior: "NEVER"
                contentHandling: "CONVERT_TO_TEXT"
                responses:
                  "200":
                    description: "200 response"
                    statusCode: 200
                    content:
                      application/json:
                        schema:
                          $ref: "#/schemas/Empty"
                credentials:
                  Fn::GetAtt: [LambdaExecutionRole, Arn]

Outputs:
  MyLambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt LambdaFunction.Arn
